version: '2'
services:
     uaa-mysql-slave:
            image: mysql:5.7.20
            volumes:
                - ~/database/ucumos/uaa-slave/mysql/:/var/lib/mysql/
                - ~/database/ucumos/uaa-slave/etc/mysql/:/etc/mysql/
            environment:
                - MYSQL_USER=root
                - MYSQL_ALLOW_EMPTY_PASSWORD=yes
                - MYSQL_DATABASE=uaa
            ports:
                - 4306:4306
            command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

    umm-mysql-slave:
            image: mysql:5.7.20
            volumes:
                - ~/database/ucumos/umm-slave/mysql/:/var/lib/mysql/
                - ~/database/ucumos/umm-slave/etc/mysql/:/etc/mysql/
            environment:
                - MYSQL_USER=root
                - MYSQL_ALLOW_EMPTY_PASSWORD=yes
                - MYSQL_DATABASE=umm
            ports:
                - 4307:4307
            command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp