version: '2'
services:
    uaa-app:
        image: uaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATASOURCE_URL=jdbc:mysql://uaa-mysql:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false
