#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to Consul running in Docker

spring:
    mail:
        host: smtp.mail.com  # 修改为自己的邮件服务器地址
        port: 25
        username: myname
        password: mypassword
        properties:
            mail:
                smtp:
                    auth: true
    zipkin:
        base-url: http://jhipster-zipkin:9411
        enabled: true

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: myname@mail.com
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds

nexus:
    maven:
        url: https://localhost:8888/repository/ucumos  # 修改为自己的Nexus服务器地址
        username: username
        password: password
    docker:
        host: localhost  # 修改为自己的Docker打包服务器地址
        port: 2375
        registryUsername: username
        registryPassword: password
        imagetagPrefix: localhost:8888  # 修改为自己的Docker服务器地址和端口号

kubernetes:
    ability:
        internalIP: localhost  # 修改为自己的kubernetes内部访问地址
    api:
        ipIpTunnelCidr: 172.16.132.192/32
        url: https://localhost:55555  # 修改为自己的kubernetes内部访问地址和端口号
        token: my-k8s-token
