serviceboot:
  version: v2

service:
  cname: API网关
  ename: gateway
  version: 2.3.0
  port: 8080

gateway:
  is_gateway: yes

build:
  image_name: gatewaypy
  build_web: no
  compile_python_to_so: no
