serviceboot:
  version: v2

service:
  cname: CubeAI个人中心
  ename: ppersonal
  version: 2.3.0
  port:
    dev: 8203
    prod: 80

build:
  image_name: ppersonalpy
  build_web: yes
  compile_python_to_so: no
