configserver:
    name: Docker Consul Service
    status: Connected to Consul Server running in Docker

spring:
    mail:
        host: smtp.mail.com
        port: 25
        username: myname
        password: mypassword
        properties:
            mail:
                smtp:
                    auth: true

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: myname@mail.com

nexus:
    maven:
        url: https://localhost:8888/repository/ucumos
        username: username
        password: password
    docker:
        host: localhost
        port: 2375
        registryUsername: username
        registryPassword: password
        imagetagPrefix: localhost:8888

kubernetes:
    ability:
        internalIP: localhost
    api:
        url: https://localhost:55555
        token: my-token