serviceboot:
  version: v2

service:
  cname: CubeAI模型共享
  ename: pmodelhub
  version: 2.3.0
  port:
    dev: 8202
    prod: 80

build:
  image_name: pmodelhubpy
  build_web: yes
  compile_python_to_so: no
