version: '2'
services:
    pdemo-app:
        image: pdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
