version: '2'
services:
    portal-app:
        image: portal
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
